name: 🐞 Bug Report
description: File a bug/issue related to the application.
title: '[BUG] <title>'
labels: ['Bug', 'Needs Triage']
assignees:
  - ''  # Leave empty or specify default assignees

body:
  - type: markdown
    attributes:
      value: |
        <!--
        Note: Please search to see if an issue already exists for the bug you encountered.
        -->

  - type: input
    id: current_behavior
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
      placeholder: Provide a description of the current behavior.

  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      placeholder: Provide a description of the expected behavior.

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the issue.
      placeholder: |
        Example:
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select the environment where you encountered the issue.
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - macOS 12 (Monterey)
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - macOS 15 (Sequoia)
        - Windows 10
        - Windows 11
        - Other

  - type: textarea
    id: additional_context
    attributes:
      label: Anything else
      description: Links, references, or anything else to provide more context.
      placeholder: Additional context or references.
