name: 🔒 Security Vulnerability
description: Report a potential security vulnerability in the application.
title: '[SECURITY] <Vulnerability title>'
labels: ['security', 'Needs Triage']
assignees:
  - ''  # Leave empty or specify default assignees

body:
  - type: markdown
    attributes:
      value: |
        <!--
        Thank you for reporting a potential security vulnerability. Please follow responsible disclosure practices by providing as much detail as possible, but do not include any sensitive information in this report. We will follow up with you privately if needed.
        -->

  - type: input
    id: vulnerability_description
    attributes:
      label: Description of the Vulnerability
      description: |
        Describe the potential vulnerability. Please include relevant details, such as how it can be exploited or how you discovered it.
      placeholder: Describe the security issue.

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide detailed steps to reproduce the issue, if applicable.
      placeholder: |
        Example:
        1. Log in as a user with limited permissions.
        2. Navigate to the admin page.
        3. Observe that restricted information is visible.

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: |
        Describe the potential impact of the vulnerability (e.g., data loss, privilege escalation, etc.).
      placeholder: Explain the potential consequences of the issue.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Add any other relevant information, such as references or related vulnerabilities.
      placeholder: Provide any additional context or details.